### ISSUE TITLE
Objective-C support

### ISSUE THREAD

**Issue by michealc** [kean/Nuke#101]
Is it possible to write a wrapper class that I can use Nuke (via cocoa pods) in an objective-c project? 
The jury seems to be out on this subject.  Apple says its possible but some people have not been able to get it to work.  Can you please advise.

**Comment by kean** [comment]
Hey, @michealc. I haven't tried using Swift from Objective-C yet, only the other way around. The former is trickier, because almost none of the Swift features can be translated into Objective-C.

For instance, from [Using Swift with Cocoa and Objective-C](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122):

> A Swift class must be a descendant of an Objective-C class to be accessible and usable in Objective-C. For more information about what you can access from Objective-C and how the Swift interface is imported, see [Swift Type Compatibility](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID53).

AFAIU, you'll need to write a Swift wrapper for Nuke which uses only primitive constructs that are compatible with Objective-C. I would suggest you use a framework written in Objective-C instead, there are plenty of those.

**Comment by michealc** [comment]
Thanks for that I am close to saying challenge accepted. So stepping it out;
1. If can write a swift class that I can use in objective-c and then,
2. Bring Nuke into the new swift class then there might be a way. Does this sound like a plan?

**Comment by kean** [comment]
Sounds about right. Just wrap the functionality you need and you should be good to go. If there'll be some changes required on Nuke's side, I'll be happy to help.
