### ISSUE TITLE
Progressive jpeg support

### ISSUE THREAD

**Issue by lgalabru** [kean/Nuke#115]
Hi Alexander,

What would be your suggestion for handling Progressive jpeg?
Same as WebP, using an external decoder? Any recommendable good citizen for that?
Best,

Ludovic

**Comment by kean** [comment]
Hey, Ludovic!

Nuke doesn't support progressive jpeg (can decode, but can't display progressively) and never will. I would suggest to look some place else, maybe something like [Concorde](https://github.com/contentful-labs/Concorde) will work for you.

In my personal opinion, progressive jpeg isn't worst it on iOS because it requires a lot of resources. A better approach for mobile would probably be to load thumbnail first, full-size image second ([here's](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Tips%20and%20Tricks.md#show-a-low-res-image-first-and-swap-to-a-higher-res-one-when-it-arrives) how to do that in Nuke). But of course that depends on the requirements that you have, that's just my thoughts.

Cheers.

**Comment by kean** [comment]
Update: it might be something that I'd consider adding as part of `Nuke 6.0` + `RxNuke 1.0`.

**Comment by kean** [comment]
Hey, @netspencer. I'm undecided on this one, there doesn't seem to be enough demand for this feature. I personally don't use it. And it's not an easy thing to implement (efficiently) and it's even harder to add it in an existing framework.

**Comment by kean** [comment]
Progressive decoding is available in [7.0-beta2](https://github.com/kean/Nuke/releases/tag/7.0-beta2). The feature is in beta.
