### ISSUE TITLE
Opt out of cancelling current request

### ISSUE THREAD

**Issue by ultimate-deej** [kean/Nuke#147]
Hi. I'm considering using Nuke. But there's one thing that stops me.

The readme says:
> `Nuke.loadImage(with:into:)` method cancels previous outstanding request for a target.

Does this also mean that rapidly scrolling a table view with images will cause dozens requests to start and cancel? That's not what I want.

Is there an option to turn off this behavior?

**Comment by kean** [comment]
Hey, @ultimate-deej!

> Does this also mean that rapidly scrolling a table view with images will cause dozens requests to start and cancel? That's not what I want.

I assume a different approach would be to not cancel requests which are already in progress? Is that what you have in mind? I've tried that as well, but I prefer the approach which is currently used in Nuke. There is a rate limiter built in - if you scroll really fast, there is only going to be a limited number of requests started each second (to avoid trashing the system).

> Is there an option to turn off this behavior?

I have it in my backlog, it can be added as an option to image `Loader`.

**Comment by ultimate-deej** [comment]
> I have it in my backlog, it can be added as an option to image `Loader`.

Thank you for the reply, looking forward to implementing this feature.
Speaking of the rate limiter, I think it will play well with cancelling disabled as well.

**Comment by kean** [comment]
I've spent some time thinking about this issue. For now, I'm not sure that this is a desirable feature. I think it makes perfect sense for Nuke to actually cancel the requests when you ask it to. Starting and cancelling requests too quickly can in fact trash URLSession to the point that it would just stop working correctly, but that problem is very well handled by RateLimiter built in Nuke. This solution is battle tested and it performs very well.

If you have a specific scenario in mind that you would like to implement, but which Nuke doens't support yet, please let me know.

**Comment by kean** [comment]
Hey @ultimate-deej! 

I'm addressing the issue that you've raised in [Nuke 7-beta1](https://github.com/kean/Nuke/releases/tag/7.0-beta1) with Resumable Downloads (Beta):

> If the data task is terminated (either because of a failure or a cancellation) and the image was partially loaded, the next load will resume where it was left off. The resumable downloads are enabled by default.

I think this is a perfect solution for the majority of use cases. There are virtually no reasons not to enable it.

Turning off cancellation on the other hand doesn't work for all apps, but it may still be useful in some. I'll continue researching this area as well.

**Comment by ultimate-deej** [comment]
Hi @kean,

This indeed seems to be the best solution.
