### ISSUE TITLE
How to remove an image from cache when using experimental aggressive cache?

### ISSUE THREAD

**Issue by filipealva** [kean/Nuke#165]
Does the code below work or it should be used only when relying on HTTP Cache?

`DataLoader.sharedUrlCache.removeCachedResponse(for: ImageRequest(url: url).urlRequest)`

**Comment by kean** [comment]
It only works with native HTTP cache (`URLCache`).

These two caches (native HTTP cache and aggressive disk cache) should be mutually exclusive. If you enable experimental aggressive cache you should also disable `native` URLCache. In order to do that you to need to create custom `ImagePipeline` with custom `DataLoader`. After your create a custom `ImagePipeline` you can set it as a shared one:

```swift
ImagePipeline.shared = ImagePipeline {
    $0.dataLoader = DataLoader(configuration: {
        let configuration = URLSessionConfiguration.default
        configuration.urlCache = nil
        return configuration
    }())
}
```

The public API for aggressive disk cache (including API for adding and removing items form cache) is going to be available in Nuke 7.2. This version will also contain a protocol which can be used to [implement custom disk caches](https://github.com/kean/Nuke/pull/163). I'm planning to release Nuke 7.2 in the end of June. The API is actually almost complete, but there is a lot of related work which need to be done including updating documentation, README, sample project and more importantly tests.

For now there is no programmatic access to `DataCache`, the only available API is `enableExperimentalAggressiveDiskCaching`.

**Comment by kean** [comment]
If you enable both native HTTP cache and custom aggressive disk cache at the same time, you'll end up storing data in both caches at the same time.

**Comment by filipealva** [comment]
Got it. I just gave the example of URLCache cleaning because I did not find any other public API to clear aggressive disk caching. 

Manually cleaning the cache is not critical for me now, so I'll give the experimental aggressive disk caching a try :) 

Just one more question: Is it safe to use aggressive disk caching on one `ImagePipeline` and URLCache on another one? I'm asking it because I'm planning to use the aggressive disk caching for static images and HTTP Cache for user profile images (as you suggested in your great Image Caching Guide). They will not be duplicated because I never will cache the same image using both methods, right?

Thank you for the hard work, this is a great library 👍

**Comment by kean** [comment]
Yes, it's safe to use more than one ImagePipeline at once, it was specifically designed to work like that.

You can even use the same `configuration`  between pipelines to make sure that the only difference between them is cache, and all the other settings are the same, including operation queue (e.g. `dataLoadingQueue`). This way you can ensure that both pipelines share the same task pools (e.g. they won't perform more than 6 data load operations at the same time).

**Comment by filipealva** [comment]
Awesome!! 

Thank you for your kind and useful answers. I'm closing the issue since I don't have more questions.
