### ISSUE TITLE
EXC_BAD_ACCESS error occurred at `stopPreheating()` after updated to 7.4.0

### ISSUE THREAD

**Issue by mono0926** [kean/Nuke#188]
EXC_BAD_ACCESS error occurred at `stopPreheating()` after updated to 7.4.0 as below:

<img width="1090" alt="screen shot 2018-09-25 at 11 17 29" src="https://user-images.githubusercontent.com/1255062/45989058-d382a180-c0b4-11e8-8042-5bd7f22e6832.png">

I'm not sure the cause yet.

It works fine in version 7.3.2.

**Comment by kean** [comment]
Haven't though this though :/

**Comment by kean** [comment]
[Published a fix](https://github.com/kean/Nuke/releases/tag/7.4.1) which disables this new feature temporarily. The story is that is was added last moment before the release and wasn't though through. You can't call `stopPreheating` in deinit of `ImagePreheater` because it calls an escaping closure which tries to retain `self.

**Comment by mono0926** [comment]
Thanks for the very quick fix 🍣
It works fine again in version 7.4.1 👍
