### ISSUE TITLE
How to check if data is cached by aggressive disk cache system?

### ISSUE THREAD

**Issue by hsakurai-cq** [kean/Nuke#198]
Hello, I'm using Nuke which is very cool swift library 😄 

Now I want to know How to check if each data is cached by aggressive disk cache system.

I can check if data is on memory
```swift
let isCachedOnMemory = Nuke.ImageCache.shared[request] != nil
```

also if data is on disk by HTTP disk cache system
```swift
let isCachedOnDisk = Nuke.DataLoader.sharedUrlCache.cachedResponse(for: request.urlRequest) != nil
```

but I can not detect if each data is on aggressive disk cache 😓

**Comment by caraquri-hsakurai** [comment]
Oh, I detected how do it 🥇 

```swift
let isCachedOnDisk = enabledDataCache?.cachedData(for: url.absoluteString) != nil
```

thanks 😄

**Comment by iago849** [comment]
This is a very bad example! You don't really check, but load it to memory. My colleague found this solution couple of years ago and our app did load 663 images instead of checking whether they exist. Use this extension: 

```
extension DataCache {
    ///  mimiced behavior from dataCache native method cachedData()
    public func hasCachedData(for key: Key) -> Bool {
        guard let _ = url(for: key) else {
            return false
        }
        return true
    }
}
```

call example: 

```
guard let cache = imagePipeline.configuration.dataCache as? DataCache else { return false }
if cache.hasCachedData(for: key) { 
....
}
```

**Comment by kean** [comment]
Hey, @iago849. Unfortunately, this isn't a correct way to check it because `url(for: key)` always returns a value, so it will always returns `true`. I'm making some additions in Nuke 10 to make this easier:

- Add `containsData(for key: String)` method to `DataCaching` and `DataCache`
- Add a new `ImagePipeline.Cache` API that simplify working with all cache layers. It has `containsImage(for request: ImageRequest)` and `containsData(for request: ImageRequest`) methods
