### ISSUE TITLE
Migration guide for v7?

### ISSUE THREAD

**Issue by guidedways** [kean/Nuke#222]
We've been using Nuke 6 in a project. I see that the migration guide is pretty much empty for v7. Any idea when it's going to be written?

**Comment by kean** [comment]
Hi, @guidedways! The was no migration guide because Nuke 7.0 was fully source compatible with Nuke 6. The idea was that Xcode would display the warnings for deprecated APIs and let you know what the new APIs are.

I removed these deprecated APIs in Nuke 7.5, more than 6 months after Nuke 7.0 was introduced. I think maybe I removed them a little bit too early and I should've done that in Nuke 8. Sorry, that's my bad.

As a solution I would suggest you upgrade to [Nuke 7.4.2](https://github.com/kean/Nuke/releases/tag/7.4.2) first. An even better alternative would be to drop this [Deprecated.swift]( https://gist.github.com/kean/a14ca485ce72bef0e50cbb2f36ec7d91) into your project and follow the instructions from the warnings.

**Comment by kean** [comment]
I updated the instructions in [Nuke 7 Migration Guide](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%207%20Migration%20Guide.md). I think using Deprecated.swift file is actually better than reading an .md file with instructions ;)
