### ISSUE TITLE
Memory leak - v8.x

### ISSUE THREAD

**Issue by sschizas** [kean/Nuke#336]
Hello,

I am using the following code to set up aggressive caching for the pipeline:

```swift
let dataLoaderConfiguration = DataLoader.defaultConfiguration
dataLoaderConfiguration.urlCache = nil
let dataLoader: DataLoader = .init(configuration: dataLoaderConfiguration, validate: DataLoader.validate)

var configuration = ImagePipeline.Configuration()
configuration.dataCache = try? DataCache(name: "com.theblueground.guestapp.DataCache")
configuration.dataLoader = dataLoader
configuration.imageCache = ImageCache()
ImagePipeline.shared = ImagePipeline(configuration: configuration)
```

I released there is a memory leak at DataLoader.init(configuration:validate:) method. 

See the attached screenshots for more details.

<img width="1437" alt="Screen Shot 2020-01-08 at 11 34 50 AM" src="https://user-images.githubusercontent.com/1173551/72018242-f61bd800-326f-11ea-9e88-caefe7fedc5d.png">
<img width="1440" alt="Screen Shot 2020-01-08 at 11 32 38 AM" src="https://user-images.githubusercontent.com/1173551/72018341-219ec280-3270-11ea-9924-f7b7f3e57166.png">
<img width="1439" alt="Screen Shot 2020-01-08 at 11 32 58 AM" src="https://user-images.githubusercontent.com/1173551/72018317-18adf100-3270-11ea-9af2-2e6a999424db.png">

**Comment by kean** [comment]
Hi, @sschizas. Thanks for the reporting. I noticed this leak too, I was not able to fix it yet. I haven't prioritized it yet since it doesn't affect memory usage – you typically only instantiate a session once per app launch.

**Comment by kean** [comment]
The issue was that `DataLoader` was not invalidating its session when deallocated. So when you were changing the data loader, the default one was not getting deallocated.

I fixed it by adding the following `deinit` method implementation in `DataLoader`:

```swift
deinit {
    session.invalidateAndCancel()
}
```

Seems like a straightforward fix. The documentation [explicitly states](https://developer.apple.com/documentation/foundation/urlsession) that session must be invalidated manually, otherwise it leaks memory.
