### ISSUE TITLE
AFNetworking integration

### ISSUE THREAD

**Issue by jdgong** [kean/Nuke#34]
AFNetworking is required by other pods. So it would be nice to keep this function as well.

**Comment by kean** [comment]
Nuke already features [Alamofire integration](https://github.com/kean/Nuke-Alamofire-Plugin). You can easily implement the same thing for AFNetworking, it would require 30 lines of code at most. You could also share it with the community (distribute via CocoaPods and/or Carthage). I'm not doing that because it's out of the scope of the framework.
