### ISSUE TITLE
Split Nuke up by functionality into subspecs 

### ISSUE THREAD

**Issue by StarLard** [kean/Nuke#373]
Please consider using cocoapod subspecs to provide a way to install just certain portions of Nuke. My team would love to use Nuke for its image cache, but we have no need of many other features, such as the image processing and view extensions. Having a way to avoid unnecessary bloat and install just the portions of Nuke we need would allow us to use it over other alternatives.

**Comment by kean** [comment]
Hi @StarLard, thanks for the suggestion. I understand there might be some perceived "bloat" associated with these features. However, Nuke is already a small framework: 

- Just ~3500 lines of code compared to ~7000 lines in some other frameworks with an equivalent feature set
- Compiles in under 3 seconds (I did invest some time into optimizing the compile time)

Even if you were to extract some of the features, the reduction in size is going to be insignificant. For example,

Sources/ImageProcessing.swift  – 501 lines of code
Sources/ImageViewExtensions.swift – 379 lines of code

If you remove these two components, you are going to save about 30 KB of text and probably around 0.3 seconds of compile time. Do you think this is worth it?

**Comment by StarLard** [comment]
Thanks for the info! Its good to know these features are lightweight. With that in mind, we can definitely re-evaluate whether Nuke is the best fit for us. That being said, cluttering our project's namespace is also a concern, as our code-base is already quite large. Being able to just have the features we need would certainly make Nuke a better contender for us (as opposed to something like [PINCache](https://github.com/pinterest/PINCache)).

**Comment by kean** [comment]
Regarding these two features, I'm intentionally keeping them light so that the users would have something to start with, but the target audience is someone who has more advanced needs and who is going to use the pipeline directly.

The processors are already neatly placed in the `ImageProcessors` namespace, so I don't think it should be a concern.

The image view extensions also designed to not extend the UIKit components too much, and all of the extensions are prefixed with `nuke_` to avoid any potential collisions in runtime. There are, however, two global methods (`loadImage(:)`). I can see the desire to not include those. So yeah, maybe making `UIKIt` extension as a subspec/module would be a good idea (I'm already doing it this way for SwiftUI integration with [`FetchImage`](https://github.com/kean/FetchImage)). But I'm not sure this change can be made in a source compatible manner which I would prefer.

**Comment by kean** [comment]
But I'm not opposed to the idea in principle, I actually quite like it. Since Nuke 9 was just released, I think it's possible to release a couple of small breaking changes now.

**Comment by basememara** [comment]
Pushing `UIKit` out the source would be a great path forward I think and help make the maintenance to core lean. Also, it may be worth reassessing the image processors in light of `SwiftUI` since I believe many are provided out of the box now.

**Comment by kean** [comment]
The split is going to happen. SPM makes it super easy. It's just a question of when (most likely Nuke 10, which I'm not sure when I'm going to start on).

**Comment by kean** [comment]
This is finally [happening](https://github.com/kean/Nuke/pull/555) in Nuke 11.
