### ISSUE TITLE
Forward caching

### ISSUE THREAD

**Issue by smhk** [kean/Nuke#385]
Love Nuke,

say you have a typical synced chat, user takes a photo, clicks SEND, uploads,

at that instant the cloud service returns what the URL **_will be_**, say

https://firebasestorage.googleapis.com/v0/b/blah2F12345678.jpg

however. that url will not actually exist for say 2 seconds.

BUT

we obviously have locally the image that **_will be at_** https://firebasestorage.googleapis.com/v0/b/blah2F12345678.jpg in a few seconds.

It would be pretty cool if you could tell Nuke:

"If you ever get asked for this URL, https://firebasestorage.googleapis.com/v0/b/blah2F12345678.jpg, in fact don't bother even going to the net. Trust me, the image is this one: .. image"

Would that perhaps be easily possible?

With this sort of **_forward caching_** (I just coined that!) you completely eliminate all the effort of doing presync stuff in synced features in apps.  Would be pretty amazing!

This would amazingly simplify typical chats, feeds etc in typical modern synced apps

Just a thought !

**Comment by kean** [comment]
Hi @smhk, that's exactly the kind of performance optimization I've been using in one of the apps I worked on. It's really effective, I think it's a must to have it.

I think there is a potential to introduce some convenience APIs to that this sort of thing. However, you can already achieve that with just the existing APIs. Things get a bit tricky because there are multiple cache layers, including custom ones.

```swift
let url = URL(string: "https://firebasestorage.googleapis.com/v0/b/blah2F12345678.jpg")!
let image = UIImage()
let data = Data() // image data

// Populate memory cache
let request = ImageRequest(url: url)
pipeline.configuration.imageCache?[request] = ImageContainer(image: image)

// Populate custom disk cache
let diskCacheKey = pipeline.cacheKey(for: request, item: .originalImageData)
pipeline.configuration.dataCache?.storeData(data, for: diskCacheKey)

// Populate native disk cache (assuming you are using the default configuration)
let response = CachedURLResponse(response: URLResponse(url: <#T##URL#>, mimeType: <#T##String?#>, expectedContentLength: <#T##Int#>, textEncodingName: <#T##String?#>), data: data)
DataLoader.sharedUrlCache.storeCachedResponse(response, for: request.urlRequest)
```

**Comment by smhk** [comment]
hi @kean 

Totally awesome, GMTA

Fantastic kode sample, thanks.

It would surely be an amazing "PR Stunt" for Nuke to include the **_ForwardCaching_** concept in a future version.

I will immediately use your code sample in a project, this is an ENORMOUS time saver when doing sync apps.

thanks and cheers!

**Comment by kean** [comment]
Added in [Nuke 10 Beta](https://github.com/kean/Nuke/releases/tag/10.0.0-beta.1) (see `ImagePipeline.Cache`).  You can now do the following:

```swift
// Stores images in memory cache (`ImageCaching`)
// Encodes and stores an image in disk cache (`DataCaching`)
pipeline.cache.storeImage(image, for: request)
```

`URLCache` support is not included because it's specific to a data loader.

Enabling a custom disk cache is not easy thanks to the new `.withDataCache` option in `ImagePipeline.Configuration`.
