### ISSUE TITLE
Completion closure is not called when the request is canceled

### ISSUE THREAD

**Issue by Waheiba** [kean/Nuke#388]
I was attempting to track the number of times I called `load​Image(with:​options:​into:​progress:​completion:​)` and decrementing that number each time the completion is called. The images are in cells in a collection view, thus there are many images being loaded.
I ended up having that counter > 0. I believe the reason for this is whenever I scroll and request is already in-progress it gets canceled to load the new one, but the completion of the first is completely dropped.
Is there any way I can identify if a request was while using `load​Image(:​:​:​:​:​)` ?

**Comment by kean** [comment]
Hi, 

> Is there any way I can identify if a request was cancelled?

You have control over when the requests get cancelled. When you call `loadImage(into:)` method, before loading a new image, the view is prepared for reuse by canceling any outstanding requests. If you need to do some cleanup/prepare for reuse work, you can do it there. If you want to know whether there was an outstanding request by the time you called `loadImage(into:)`, it's going to be more tricky.

The reason completion closure is designed this way is that by the time the decision was made there was no consensus how to design these sort of APIs. Many Apple APIs would not call completion on cancellation. Now I'm leaning towards calling a `completion`. I never made this change because it is breaking and there were no requests from the users.

If you need this for analytics, there is an `ImagePipelineObserving` protocol which communicates `cancelled` along with other terminal events.

**Comment by Waheiba** [comment]
@kean I believe this answers my question :] thank you so much.
I'm able to track everything happening now about the events through the observer on the shared `ImagePipline`
And I can understand the pain clearly about the breaking change for calling `completion` and it's very unlikely that there would ever be a need to check if a request is already loading on an image or not.
