### ISSUE TITLE
416 range error

### ISSUE THREAD

**Issue by mtrezza** [kean/Nuke#389]
### Issue

I see a significant amount of `416 Range Not Satisfiable` logs with our CDN. These errors only occur in the iOS app with Nuke, not in the Android app with Glide, which is loading the same images. However, I have not seen any issues with image loading in the app and there are no user complaints about images not loading.

### Logs

Status | Timestamp | Remote IP | Size | Path
-- | -- | -- | -- | --
416 | 2020-07-31 01:55:42 | (REDACTED) | 598 Bytes | (REDACTED)

The "size" in the logs which I assume is the requested range is always around 400 - 600 Bytes for these 416 errors.
For successful CDN responses, "size" is the actual image size, like several KB.

### Question

Are there any cases in which Nuke uses range requests?

**Comment by kean** [comment]
Hi, yes, by default Nuke uses [range requests](https://github.com/kean/Nuke/blob/master/Sources/Internal.swift#L255) and this error code is most likely related to them. To disable it, you can set `isResumableDataEnabled` to `false` on the pipeline configuration. However, it would be great to investigate and try to fix it.

**Comment by kean** [comment]
Nuke has a very [simple algorithm](https://github.com/kean/Nuke/blob/master/Sources/Internal.swift#L298) for setting requested ranges, I'm not sure what can be wrong with the range.

**Comment by cjmconie** [comment]
Hi, I am experiencing a similar issue. 

It seems to appear when there are concurrent requests, for example inside a `UICollectionView` displaying a grid of `UICollectionViewCell`s . I'm using `Nuke.loadImage(with:into:)`. `ImagePipeline` is unmodified. Images are being requested directly from Firebase Storage. The error from Nuke is: `Failed to load image data: Response status code was unacceptable: 416`

Customising the `ImagePipeline` by setting `isResumableDataEnabled` as `false` resolves the issue.

Is there any more information I can provide to help?

**Comment by mattczech** [comment]
Hello, I'm also seeing occasional 416 errors.

In my case, I'm loading images stored in S3. Each 416 that I've observed is a result of Nuke requesting a starting byte count that is equal to the size of the image.

I'm using a `UICollectionView` to display a grid of images with `Nuke.loadImage(with:into:)`. No modifications to the pipeline.

When I've seen the error, I've observed the following:

- The image exists in the URLCache and it's not expired.
- The collection view's initial layout occurs, cells are configured and images start loading. During this, one of the cells starts loading a different image.
- This cancels the original request while it's loading from the cache. It looks like the received data is then saved to `ResumableData`. The next time this image is loaded, it attempts to resume that request but since the full image data was saved as resumable data, it sends a range header with the starting offset equal to the size of the image, which is one byte past the last byte in the image.

Nuke 9.1.2

**Comment by mtrezza** [comment]
Well researched! That looks like a bug, it that is really the case.

**Comment by kean** [comment]
Hi, @mattczech. Thank you for providing this info. I went through the code and it does seem to be the case that the situation you are describing is possible. I'm going to address this issue in the upcoming release.

**Comment by kean** [comment]
I opened a PR with a fix https://github.com/kean/Nuke/pull/402/files
