### ISSUE TITLE
Image rendering/networking issue across the OS

### ISSUE THREAD

**Issue by sjmueller** [kean/Nuke#440]
Our app is experiencing some sort of severe cache corruption where all images go blank. Even more concerning, the user's entire phone is affected. Here's more info:

<img width="2241" alt="image" src="https://user-images.githubusercontent.com/29085/107994964-958ebc80-6f92-11eb-8d3a-bf585f2d7263.png">

Our Nuke configuration in `AppDelegate` is as follows:
``` swift
ImagePipeline.shared = ImagePipeline {
    $0.dataLoadingQueue.maxConcurrentOperationCount = 12 // Default is 6
    $0.dataCachingQueue.maxConcurrentOperationCount = 5 // default is 2
    $0.imageDecodingQueue.maxConcurrentOperationCount = 3 // default is 1
    $0.imageEncodingQueue.maxConcurrentOperationCount = 3 // default is 1
    $0.imageProcessingQueue.maxConcurrentOperationCount = 5 //default is 2
    $0.isDeduplicationEnabled = true // Combine the requests for same original image into one.
}

ImageCache.shared.costLimit = 1024 * 1024 * 250
ImageCache.shared.countLimit = 500
ImageLoadingOptions.shared = ImageLoadingOptions(transition: .fadeIn(duration: 0.2))
```

Out of desperation, we are currently testing an alternative config that doesn't use HTTP caching, since it seems like that is the only way this could be correlated to other apps:
``` swift
    // Attempt to combat prominent "image disappearing" bug in prod by disabling the native HTTP cache in favor of LRU Disk Cache
    $0.dataLoader = DataLoader(configuration: {
        // Disable disk caching built into URLSession
        let conf = DataLoader.defaultConfiguration
        conf.urlCache = nil
        return conf
    }())
    
    $0.dataCache = try? DataCache(name: "app.blink")
```

## More info
I've had the opportunity to debug the app while in this state, and unfortunately I don't see any errors in the console that would give clues. However, what I have noticed is that break points in the callback may not be getting invoked:
``` swift
Nuke.loadImage(with: url, into: imageView) { result in
    switch result {
    case .failure(let error): print(error)
    case .success(_): break
    }
}
```

This problem has only been observed for the past few months, after iOS 14 was released. It's really hard to tell the exact moment though, whether it was a Nuke upgrade, operating system version, or app change. Do you have any advice or insight as to what may be occurring?

**Comment by kean** [comment]
I'm not sure how this is even possible. I would like to think that Nuke is not the root cause, but there is, of course, always a possibility.

I don't think it's related to caching because the cache is still confined to the app. It might be related to something that has to do with CoreGraphics. But from the top of my head, there is nothing particularly interesting that Nuke does neither when it comes to networking, nor graphics. There is no use or private APIs, no swizzling, nothing like that. It's all pretty straightforward code that you can find in any app.

One of the few guesses that I have is that it might have to do with decoding. Decoding is hardware accelerated and in some early iOS versions it was not thread safe. I would suggest to change `imageDecodingQueue` operation count to 1 and see if this helps.

Is there a way to reproduce it? Do you think your app is the root cause? Do you know which iOS versions are affected? Do you have any other image/network related frameworks in your app?

**Comment by kean** [comment]
Have you opened a radar with Apple? I'm also going to look if there are any other related reports somewhere on GitHub.

**Comment by sjmueller** [comment]
Thanks for the quick response @kean. I have not opened up a radar with Apple, as it has been so strange to even pinpoint if it was our app. As mentioned before, we are testing `DataCache` LRU Disk Cache to see if things improve -- so far I have not experienced the problem but one of our testers claimed that she had. I am putting out another release with your suggestion of `imageDecodingQueue.maxConcurrentOperationCount` down to 1 and seeing what happens with our beta testers.

On exploring a CoreGraphics corrupt state, wouldn't that affect local images as well? The reason why I initially suspected cache is because local images (inside of `Assets.xcassets`) continue to render just fine, despite remote images actively having problems. Plus Apple would likely be using `URLCache` as well in the App Store app.

**Comment by kean** [comment]
It can depend on the image format. Local assets are typically png files that don't require decompression that jpg files do. I'm suspecting jpeg decompression, but purely based on intuition. It can be anything.

**Comment by kean** [comment]
If it's remote images, it can also be networking.

**Comment by sjmueller** [comment]
We use Alamofire for most of our networking and our images are mainly heif, all in AWS S3. However we almost exclusively use `Nuke.loadImage` which I believe has no knowledge of Alamofire?

**Comment by kean** [comment]
No, it uses URLSession with a default configuration.

**Comment by sjmueller** [comment]
An update, we have rolled out this configuration change and have not seen the disappearing image failure since:

``` swift
ImagePipeline.shared = ImagePipeline {
    $0.dataLoadingQueue.maxConcurrentOperationCount = 20 // Default is 6
    $0.dataCachingQueue.maxConcurrentOperationCount = 8 // default is 2
    $0.imageDecodingQueue.maxConcurrentOperationCount = 1 // default is 1
    $0.imageEncodingQueue.maxConcurrentOperationCount = 5 // default is 1
    $0.imageProcessingQueue.maxConcurrentOperationCount = 8 //default is 2
    $0.isDeduplicationEnabled = true // Combine the requests for same original image into one.
    
    // Attempt to combat prominent "image disappearing" bug in prod by disabling the native HTTP cache in favor of LRU Disk Cache
    $0.dataLoader = DataLoader(configuration: {
        // Disable disk caching built into URLSession
        let conf = DataLoader.defaultConfiguration
        conf.urlCache = nil
        return conf
    }())
    
    $0.dataCache = try? DataCache(name: "app.blink")
}

ImageCache.shared.costLimit = 1024 * 1024 * 250
ImageCache.shared.countLimit = 1000
ImageLoadingOptions.shared = ImageLoadingOptions(transition: .fadeIn(duration: 0.2))
```

I personally did not see the issue again after `urlCache` was disabled in favor of `DataCache`, so I can't say for sure if reducing `imageDecodingQueue` down to 1 helped at all. Either way, the issue has been resolved by *only* changing Nuke configuration. Whether this is a bug in iOS or Nuke, it is *very* scary to affect other apps and I hope that somehow we can figure out definitively what is the root cause, so other's can avoid the pains we experienced recently.

**Comment by kean** [comment]
That's great news, thanks for following up on this.

What I can do from my side is deprecate and make private `imageDecodingQueue` and `imageEncodingQueue`. I don't have a lot of trust in these APIs since the last issue with decoding. You can find more information here https://github.com/kean/Nuke/pull/277/commits. It was a major issue prior to iOS 10 and all frameworks were affected.

I don't know whether I should or whether I even can do anything about URL cache.

By the way, the `maxConcurrentOperationCount` values that are set seem very aggressive. Have you measured how this affects performance? You don't want to trash the system with too much concurrent work.

For example, when I measured different `imageProcessingQueue` configurations, I found that for most processors there were about 2x difference 1 and 2, not a big difference between 2 and 3, and barely any difference between 3 and 4 concurrent operations. So I went with a more conservative default, 2.

**Comment by kean** [comment]
That's great news, thanks for following up on this.

What I can do from my side is deprecate and make private `imageDecodingQueue` and `imageEncodingQueue`. I don't have a lot of trust in these APIs since the last issue with decoding. I can't find a link right now, but it was a well-known issue and all frameworks were affected.

**Comment by sjmueller** [comment]
I also can confirm that the issue was occurring with multiple remote image types: `png` `heif` and `jpg`. I keep thinking about what could possibly affect remote images only in multiple apps (including the Apple App Store app), and the common element is most likely `URLCache`. I don't fully understand how `URLCache` spans the operating system or how it might be possible to corrupt in a global context, but we had dozens of users confirm the bug so it is definitely possible.

**Comment by kean** [comment]
Sorry accidentally closed this, something went wrong with GiHub web interface. I think it's a bit premature to close.

**Comment by kean** [comment]
> I don't know whether I should or whether I even can do anything about URL cache.

Actually, I do have an option. I was considering changing some of the default configuration options for Nuke 10. One of the things I wanted to do is completely disable URLCache and enable a custom aggressive cache. I think this should work best for most apps. Most apps don't need HTTP caching. And Nuke's custom cache is significantly faster than URLCache.

**Comment by sjmueller** [comment]
> By the way, the `maxConcurrentOperationCount` values that are set seem very aggressive. Have you measured how this affects performance? You don't want to trash the system with too much concurrent work.

We have an animated emoji picker with a few hundred `.apng` images, and it serves as our benchmark for image loading. We were forced to get aggressive because of how much time it was taking for the collection view to show images, and it's very obvious that concurrency limits were being hit. We've done a ton of work to reduce the file sizes, dimensions as small as possible, etc.

To be honest it is still not where we want it to be -- maybe we'll be forced to use a different methodology than loading each `apng` individually.

**Comment by sjmueller** [comment]
> Actually, I do have an option. I was considering changing some of the default configuration options for Nuke 10. One of the things I wanted to do is completely disable URLCache and enable a custom aggressive cache. I think this should work best for most apps. Most apps don't need HTTP caching. And Nuke's custom cache is significantly faster than URLCache.

I tend to agree with you here. I did have some comfort in the idea of using native built-in HTTP caching, and there was definitely mental friction moving away from it. But since the move, I have noticed a slight perceptible performance gain with the custom cache -- and as you probably can guess -- performance is king 😍

**Comment by sjmueller** [comment]
Bad news to report: despite a temporary reprieve in occurrences, I just experienced the issue a few times, requiring me to restart the app. Others are now reporting the same. Are there more conservative settings you recommend? Should I just take all the OperationCount variables back to their defaults?

**Comment by kean** [comment]
I opened [a radar](https://user-images.githubusercontent.com/1567433/108305629-6c2f8580-7178-11eb-99b7-6140b33e602e.png) (haven't copied to openradar yet), please let me know if I should add any more details. I also contacted SDWebImage maintainer, maybe he has some insights.

> Are there more conservative settings you recommend? Should I just take all the OperationCount variables back to their defaults?

I would recommend switching to defaults with except for the data cache. You don't want to trash the system. That reminds me, there is, or at least used to be, possible to trash `URLSession` by resuming and cancelling too many requests too quickly to the point where it couldn't serve any requests anymore. This is why Nuke has a rate limiter built-in, so regardless of how many concurrent operations you set, it shouldn't trash the system.

> We have an animated emoji picker with a few hundred .apng images

This sounds like a potential root cause. What are you using for rendering those? Animated images can be very resource-heavy. If it's feasible for you, I would recommend briefly switching to SDWebImage and the same `apng` rendering engine and see if it makes a difference.

**Comment by sjmueller** [comment]
We are using [CGAnimateImageAtURLWithBlock](https://developer.apple.com/documentation/imageio/3333271-cganimateimageaturlwithblock) to render animated apngs, which I also thought might be the culprit. However, during the corrupt state, the animated images happen to be the only remote images that work! They consistently render when everything else doesn't. So I highly doubt they are the culprit, but this may give clues in understanding which systems might be in failure and which aren't.

We will switch to defaults on everything as you recommend, except for the data cache. I will report back any changes in app behavior once apple approves the build for release and it's in the hands of more users.

**Comment by sjmueller** [comment]
As for the radar link, I would mention:
- there are various image types being downloaded remotely (mainly heif, some jpg, some png)
- Remote animated apng images are also downloaded and rendered with CGAnimateImageAtURLWithBlock but they are unaffected during the corrupt state and render correctly
- The images disappear across multiple apps, including the Apple App Store app
- The only surefire way to get images rendering again is via a full restart of the entire iPhone
- This has been observed on various devices, from iPhone 7 to iPhone 12 Pro Max
-

**Comment by kean** [comment]
Some insights:

> Maybe the Springboard process is affected? Or the CoreAnimation render server process crashes. The render server process is used when you draw CGContext and CGImage on it, which use mmap to allocate the actual RAM. But typically if you render too many CGContexts, your App process will be terminated or the iPhone will respring (Spingboard will restart)

**Comment by sjmueller** [comment]
We had a breakthrough on the issue today, and have determined that **Nuke has nothing to do with the problem**. The root cause actually stems from Android, where heif images are being generated by users on our Android app using Jetpack's Heifwriter lib (1.1.0-alpha01). It seems on occasion this library generates an image that can take down a large subsystem of iOS simply by rendering the image, requiring a full reboot of the iPhone in order to get images rendering again.

Big thanks to @kean for working with us to figure out the problem and submit Radars to Apple. We'll also reach out to Google to let them know what's happening with their `Heifwriter` library.
