### ISSUE TITLE
Attempted to read an unowned reference but the object was already deallocated

### ISSUE THREAD

**Issue by dotWasim** [kean/Nuke#509]
I get this error when LazyImage disappear in SwiftUI

https://www.dropbox.com/s/h8w29qidnsq1tss/Screen%20Shot%202021-09-23%20at%2012.23.05%20PM.png?dl=0#

**Comment by kean** [comment]
Hey, could you please provide a sample where this issue can be reproduced? I think it might be related to the way it's used.

**Comment by sebastien-tribu** [comment]
In case it can be of inspiration to others I had this crash recently and it got fixed by changing my usage of `ImagePrefetcher`.

I have a `journal` object which holds a list of image URLs.
Only one journal is in memory at a time. When the user loads another `journal`, the prefetcher may not have finished prefetching all the previous URLs! 
The fix was to add `[weak self]` before calling my prefetcher and make sure no work is done on no-longer-existing URLs, like so

```
        $journal
            .compactMap { $0 }
            .sink { [weak self] in
                self?.imagePrefetcher.startPrefetching(with: $0.allURLs)
            }
            .store(in: &cancellables)
```

Hope this helps
