### ISSUE TITLE
Integration guide

### ISSUE THREAD

**Issue by Gargo** [kean/Nuke#659]
Add integration guide into tutorial please

**Comment by kean** [comment]
Hi, there is a [Getting Started](https://kean-docs.github.io/nuke/documentation/nuke/getting-started). If you think there is something missing, I would appreciate the suggestions how to improve it.

**Comment by Gargo** [comment]
@kean It is not the integration guide. You missed a part how to add Nuke to Xcode and jump to writing code for Nuke which is already imported into project.
I saw `Package.swift` file in this repo and added Nuke to my project via Swift Packages but I still don't know is it correctly. Maybe you dropped support of this way at all.

In other words just look at this random repo:
https://github.com/SDWebImage/SDWebImage
Does your readme or documentation contains "Installation" part?

**Comment by kean** [comment]
That's a good point. I think having an installation guide used to be important when you had to use a third-party tool, e.g. CocoaPods. But Nuke, as well as the rest of my frameworks, support only SPM. I don't think it requires an installation guide because it's a first-party tool provided and documented by Apple.

**Comment by Gargo** [comment]
@kean 
Then at least could you please write something like (it is not obvious):

Installation:
- using Swift Package Manager

**Comment by kean** [comment]
Absolutely, I'll add a section to either README or the Getting Started guide.
