### ISSUE TITLE
LazyImage - Main actor-isolated property 'image' can not be referenced from a non-isolated context

### ISSUE THREAD

**Issue by theedov** [kean/Nuke#678]
Hi, I'm getting errors when trying to use NukeUI LazyImage in SwiftUI View.
Do I really need to add `@MainActor`? Haven't seen it being used in swiftui views.

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/30866972/222032368-bbbd1248-8a57-4f29-a327-4ae1ce571b6c.png">

**Comment by adriansergheev** [comment]
looks like it's fixed in: https://github.com/kean/Nuke/pull/664

**Comment by kean** [comment]
I suggest moving these methods to the parent View or adding a `@MainActor` attribute to them.

`LazyImage` and `FetchImage` both have a `@MainActor` attribute because that's how they are intended to be used. But I think it's worth re-evaluating this decision. I'm not sure what the pros/cons are going to be of removing the `@MainActor` attribute.

**Comment by kean** [comment]
I'm going to close it because both of these types are confined to the main thread, and it makes sense to enforce it using `@MainActor`.
