### ISSUE TITLE
Can I know more about Nuke 4?

### ISSUE THREAD

**Issue by joe528** [kean/Nuke#77]
I have been using Nuke 3 in one of my released app. Everything works great! What a great work.

Now I see you have published Nuke 4, and I have some questions:

(1) Do you recommend to update the app to use Nuke 4? What are the primary benefits if I do so? (The app is like a news app that uses Nuke to download images used in a table view. Preheat feature is also used.)

(2) Right now it's in beta 1, how's the progress and what is the plan for future releases? Should I wait for the general release or should I start with beta?

**Comment by kean** [comment]
> Do you recommend to update the app to use Nuke 4?

Nuke 4 is written in Swift 3 (Nuke 3 isn't). If you update your app to Swift 3, you'll have to update to Nuke 4.

> What are the primary benefits if I do so?

Like I've [mentioned](https://github.com/kean/Nuke/issues/74#issuecomment-240370757), I wanted to make Nuke a micro-framework (in contrast with other frameworks).

Feature-wise it's very similar to Nuke 3.

Implementation has changes a lot. Here's a couple of most meaningful changes:

- Nuke 3 promised a lot of customization using protocols, however those protocols were vaguely defined and hard to implement in practice. Nuke 4 has a much, much simpler model. I really enjoy it and it helped me write more and better unit tests.
- Nuke 4 now uses `Promise` for managing async operations, and `CancellationToken` as a unified model for cancelling operations. It resulted in a more concise code which is much easier to understand.
- I've generously applied single responsibility principle. For example, instead of packing preheating and deduplicating of equivalent requests in a single vague `Manager` class they are now implemented as a separate classes (see `Preheater`, `Deduplicator`). It makes the core classes much easier to reason about.

> The app is like a news app that uses Nuke to download images used in a table view. Preheat feature is also used.

Migration should be very straightforward. Just follow the new [usage guide](https://github.com/kean/Nuke#usage) and check out `Request.swift` file.

> Right now it's in beta 1, how's the progress and what is the plan for future releases? Should I wait for the general release or should I start with beta?

It's almost finished. I'm going to release Nuke 4 some time after Xcode 8 release. I really hope to get some feedback before that happens. Chances are I've missed something 😄

**Comment by kean** [comment]
I'm also planning to implement a custom LRU memcache. I currently use NSCache which [is not LRU](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSCache.swift), and which is pretty slow, because I have to [wrap my keys](https://github.com/kean/Nuke/blob/master/Sources/Cache.swift#L87) (which are structs) into objects. I'll ship it with beta2.

**Comment by joe528** [comment]
Sounds great. I will update to Nuke 4 and provide you feedback if any.

**Comment by kean** [comment]
I would suggest waiting till beta2 though, I'll release it by the end of the day.

**Comment by kean** [comment]
[4.0-beta2](https://github.com/kean/Nuke/releases/tag/4.0-beta2) is out

**Comment by kean** [comment]
FYI, I've written an in-depth [Nuke 4 Migration Guide](https://github.com/kean/Nuke/blob/master/Docs/Nuke%204%20Migration%20Guide.md).
