### ISSUE TITLE
Missing documentation for using LazyImage implementation inside Package

### ISSUE THREAD

**Issue by michael-martinez** [kean/Nuke#771]
We lost some time trying to find how to import the library inside Package.swift.
This would be great to include some documentation doing so in the README file (which would avoid importing the deprecated NukeUI repository):

dependencies: [
    .package(url: "https://github.com/kean/Nuke.git", exact: "12.4.0"),
]

.target(
    dependencies: [
        .product(name: "NukeUI", package: "Nuke"),
    ]
)

Also some simple examples showing how to use it would be great.

**Comment by kean** [comment]
Hey, @michael-martinez .

The Getting Started guide is available [here](https://kean-docs.github.io/nuke/documentation/nuke/getting-started/), and there is a great number of other articles hosted in the same place, as well as a complete API documentation.

Im considering how to include a better guide on installation. I typically avoided added extended guides for my previous and current frameworks because there are no special instructions needed, but it might be worth explaining what modules to use and when.

**Comment by kean** [comment]
I added a list of modules to the README file as well as the link to the Getting Started guide.
