### ISSUE TITLE
Draft last Nuke 3 release that targets Swift 2.3

### ISSUE THREAD

**Issue by adomanico** [kean/Nuke#79]
Can you draft a new release with Nuke 3 that supports Swift 2.3?

Currently having our dependency manager use the branch 'swift2.3' which isn't very concrete.

Thanks!

**Comment by kean** [comment]
Will do. I should test it with Xcode 8 GM first though.

**Comment by adomanico** [comment]
Great thanks!

**Comment by kean** [comment]
I've added [3.2 tag](https://github.com/kean/Nuke/releases/tag/3.2), but I can't push it to trunk, because CocoaPods still seems to be broken (as of 1.1.0.beta.2).

P.S. I would really encourage you to check out [Nuke 4](https://github.com/kean/Nuke/releases/tag/4.0-beta2). I would also greatly appreciate some feedback.

**Comment by kean** [comment]
Yay, I finally managed to push Nuke 3.2 spec.
