### ISSUE TITLE
Feature Request: Logging for image request

### ISSUE THREAD

**Issue by prabhuamol** [kean/Nuke#800]
Hi,
Is there an easy way for us to log time for each image requests in a LazyImageView (start, complete, fail) via a delegate or something? We basically want to track when the request starts and finishes or fails via an LazyImageView. Its much easier to do via ImagePipeline.loadImage call via a compltion block but not sure how to do that using a LazyImageView

**Comment by kean** [comment]
There is none. The closest thing it has is support for OSLog signposts. This has been a common request, so I'm re-opening this. 

I wish [swift-log](https://github.com/apple/swift-log) was part of the standard library because then I would use it, but I'm not including a dependency just for logging. I'm open to suggestions how to implement it.

The closest thing that's currently available to logging is the pipeline delegate and namely its [imageTask(_:didReceiveEvent:pipeline:)](https://kean-docs.github.io/nuke/documentation/nuke/imagepipelinedelegate/imagetask(_:didreceiveevent:pipeline:)-2t77r) method.

**Comment by prabhuamol** [comment]
> pipeline

So what we ended up doing was to use `didCompleteWithResult` delegate on `ImagePipeline`. We had to basically mark some trace as complete or fail depending on the result. We passed that object as part of the `userinfo` for the task. And then in the delegate got that back and marked it

```
func imageTask(_ task: ImageTask, didCompleteWithResult result: Result<ImageResponse, ImagePipeline.Error>, pipeline: ImagePipeline) {
        Task {
            if let timer = task.request.userInfo[.renderTimer] as? RenderTimer {
                switch result {
                case .success:
                    await timer.complete()
                case .failure:
                    timer.fail()
                }
            }
        }
    }
```

**Comment by prabhuamol** [comment]
> LazyImageView

Also looks like LazyImageView does have onStart, onCompletion, onFail, onSucess callbacks. Wonder if that could have worked as well
