### ISSUE TITLE
Progress Bar W/ Nuke 4?

### ISSUE THREAD

**Issue by bassrock** [kean/Nuke#81]
I may be blind but it looks like Nuke 4 removes the ability to use a progress handler?

**Comment by kean** [comment]
You are right. I'm still undecided on this feature so I've removed it, probably just temporarily. That's one of the reasons Nuke 4 is still in a beta.

As a workaround I would suggest to show simple activity indicator instead of a progress bar:

```swift
let indicator = activityIndicator(for: cell)
        
indicator.startAnimating()
Nuke.loadImage(with: request, into: imageView) {
    // Manager holds a weak reference to a target
    imageView.handle(response: $0, isFromMemoryCache: $1)
    indicator.stopAnimating()
}
```

Sorry if this hurts the transition.

**Comment by kean** [comment]
![pill3](https://cloud.githubusercontent.com/assets/1567433/19457156/adeb407c-94cd-11e6-93fd-763d88aa873c.png)

**Comment by ksm** [comment]
@kean Any protips on how one would go about extending Nuke with a progress closure? 

Looking through the source code I'm guessing I would need to implement `DataLoading`, then instantiate a Loader with that `DataLoading` implementation.

So API for progress could be:
```swift
request.progress = { progress in
}
```

**Comment by kean** [comment]
@ksm hey, unfortunately, I'm still undecided on this feature. Here are some of my points:

1. Built-in `DataLoader` doesn't support progress reporting. In order to support progress it needs a bunch of new code. Namely, it needs to use `NSURLSessionDelegate` family of protocols (which would complicate things).
2. It doesn't seem right to just add a `progress` closure to the `Request` unless default `DataLoader` actually supports it.
3. You should also take into account `Deduplicator` - it combines multiple `Requests` with the same `loadKeys` into a single request. This fact also complicates progress reporting (especially closure-based). `Deduplicator` is enabled by default.
4. You can implement progress reporting without changing any of Nuke's code by adding a custom `DataLoader`.  You can either pass progress closure via `Request.userInfo`, or you can fire progress notifications from your `DataLoader`.

Hope this makes sense.

**Comment by ksm** [comment]
@kean Thank you for the pointers!

**Comment by kean** [comment]
Update: this issue is planned for `Nuke 6.0`.

**Comment by kean** [comment]
Added in [Nuke 6.0-beta1](https://github.com/kean/Nuke/releases/tag/6.0-beta1). The API is:

```swift
request.progress = { completed, total in
}
```

> Sorry that it took me more than a year 😅

**Comment by ksm** [comment]
Thank you for the update on this. This is great.
