### ISSUE TITLE
Extensions to UI components in Nuke 4?

### ISSUE THREAD

**Issue by bmetitiri** [kean/Nuke#87]
I'm curious about the architecture change to remove the nk_ extensions from UIImageView since it's something that initially attracted me to this library, and I got a ton of use out of it. 

For instance, my app is mostly images in table cells, so in cellForIndexPath I would just call nk_setImageWith, and in the cell's prepareForReuse I would just call nk_cancelLoading and it was very simple and elegant and great for memory consumption. It seems that to do the same thing without a UIImageView extension, I would need to add at least one CancellationTokenSource property to each custom table cell and keep track of it, which is fairly verbose and inelegant. 

I can of course just implement some extensions myself so I don't have to manage CancellationTokenSources, but I was wondering if the extensions had caused some subtle issue that was fixed by removing them? I also noticed that the extension for FLAnimatedImageView is still around, is that intentional or will that be removed soon as well?

**Comment by kean** [comment]
Hey, @bmetitiri! Managing reuse of views is one of Nuke's primary features. I'm never removing it and I have plans to extend it beyond what other frameworks do.

From [Nuke 4 Migration Guide](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%204%20Migration%20Guide.md) (check it out!):
> Instead of adding extensions to UI components Nuke now has a `Manager` class which loads images into specific targets (see new `Target` protocol which replaced `ImageLoadingView` and `ImageDisplayingView` protocols).

```swift
// Nuke 3
let request = ImageRequest(URLRequest: NSURLRequest(NSURL(URL: "http://...")!))
imageView.nk_setImageWith(request)

// Nuke 4
let request = Request(urlRequest: URLRequest(url: URL(string: "http://...")!))
Nuke.loadImage(with: request, into: imageView)

// Nuke 4 (NEW)
// Use custom handler, target doesn't have to implement `Target` protocol.
Nuke.loadImage(with: request, into: imageView) { response, isFromMemoryCache in
    // Handle response
}
```

There are multiple reasons behind the change, just to name a few:

- `Manager` class has context about all the requests per all targets (or just targets per screen if you create a `Manager` per screen). It will allow me to add features like: _lower the priority of the requests when the UIVC goes off screen_. That's something I really want in Nuke and it also something that works extremely well in practice.
- `ImageView` no longer "loads images in itself". So Nuke doesn't break MVC.
- I don't have to prefix methods.
- Nuke 3 had elaborate `ImageLoadingView` and `ImageDisplayingView` protocols. They had lots of methods, some implemented by default, some added in extensions. It was a mess. New `Manager` -> `Target` relation is super simple and feels natural.

I always felt like adding extensions to `UIImageView` that would do something as complicated as loading images was abusing an extensions system. The reason why other frameworks implement it this way is because this is how it was initially implemented in `SDWebImage` (which was and is a terrible tangled mess of code).

**Comment by kean** [comment]
> I also noticed that the extension for FLAnimatedImageView is still around, is that intentional or will that be removed soon as well?

You now also use `Manager` class (you can think of is as `Nuke.ControllerThatLoadsImagesIntoTargets`, that's all it does really):

```swift
let view = AnimatedImageView()
AnimatedImage.manager.loadImage(with: URL(string: "http://...")!, into: view)
```

The only extension method which is left is `public func nk_display(_ image: Image?)` which just starts an animated image playback.

**Comment by kean** [comment]
And about `prepareForReuse`. This method gets called right before `cellForItemAt:`.

```swift
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
    // View reusing is handled automatically
    Nuke.loadImage(with: url, into: cell.imageView)
}
```

`Nuke.loadImage(with:into:)` method automatically cancels previous outstanding request associated with the target. Which means that you don't have to implement `prepareForReuse` yourself.

You can also (optionally) implement `didEndDisplaying:forItemAt:` method to cancel the requests as soon as the cell goes off screen:

```swift
func collectionView(_ collectionView: UICollectionView, didEndDisplaying cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
    Nuke.cancelRequest(for: cell.imageView)
}
```

**Comment by bmetitiri** [comment]
> You now also use `Manager` class:

>``` 
let view = AnimatedImageView()
> AnimatedImage.manager.loadImage(with: URL(string: "http://...")!, into: view)
```

But you can't use `AnimatedImageView` in a storyboard right? Because it doesn't have `initWithCoder`? I used the `loadImage` completion handler and called `nk_display` myself, that seems to work well. 

Thanks for the explanation. Looking forward to seeing where you take this.

**Comment by kean** [comment]
> But you can't use AnimatedImageView in a storyboard right? Because it doesn't have initWithCoder? 

I've added support for Storyboard in `AnimatedImageView`, will be available in v2.1.

**Comment by lubos08** [comment]
@kean Have you release v2.1?

**Comment by kean** [comment]
@lubos08, I just did, enjoy

**Comment by lubos08** [comment]
@kean Thank you for your support.

**Comment by lubos08** [comment]
@kean I have one more question.
I'm using AnimatedImageView in my tableViewCell, but I got this error.
```
required public init?(coder aDecoder: NSCoder) {
        fatalError("AnimatedImageView doesn't support NSCoding yet")
}
```

How can I fix this?

**Comment by lubos08** [comment]
@kean  wow, still is not the latest version...

**Comment by lubos08** [comment]
@kean Your demo project pulling latest code, but I'm not sure why my project is not pulling latest code...
Please help me.

**Comment by kean** [comment]
Have you figured out what the problem was? Do you use `pod update`?

**Comment by lubos08** [comment]
@kean Thanks for your update.
`pod update` worked for me!
