### ISSUE TITLE
Remove animation when loadImage not from memory cache.

### ISSUE THREAD

**Issue by lubos08** [kean/Nuke#96]
Hi @kean,

I'm using your library for my app, and really love to work with Nuke.
But I have one problem during using your library.

I found this code.
```
extension ImageView: Target {
        /// Displays an image on success. Runs `opacity` transition if
        /// the response was not from the memory cache.
        public func handle(response: Response, isFromMemoryCache: Bool) {
            switch response {
            case let .fulfilled(image):
                self.image = image
                if !isFromMemoryCache {
                    let animation = CABasicAnimation(keyPath: "opacity")
                    animation.duration = 0.25
                    animation.fromValue = 0
                    animation.toValue = 1
                    let layer: CALayer? = self.layer // Make compiler happy on macOS
                    layer?.add(animation, forKey: "imageTransition")
                }
            case .rejected(_): return
            }
        }
    }
```

Can you please disable animation when it's loaded from web?
Or at least, can you make me possible to disable it by setting some flag?

Thank you.

**Comment by kean** [comment]
Hey @lubos08, just provide a custom handler:

```swift
Nuke.loadImage(with: request, into: view) { [weak view] response, _ in
    view.image = response.value
}
```

If you want to reuse this code just extract it to a function.

`loadImage(with request: Request, into target: AnyObject, handler: @escaping Handler)` method is super flexible, this is why I don't provide much of the built-in options. Maybe I'll remove the default animation too in Nuke 5. Can't do it right now because of backward compatibility.

**Comment by lubos08** [comment]
@kean, Thanks for your quick response! 
Really appreciate for your support.
