### ISSUE TITLE
LinkedList<CachedImage> leaked

### ISSUE THREAD

**Issue by n3trino** [kean/Nuke#99]
At Cache.swift the xcode memory grapher tool shows that there is a leak at line
`private let list = LinkedList<CachedImage>()`

Check the attached screenshot:
![screen shot 2016-12-13 at 16 50 07](https://cloud.githubusercontent.com/assets/1173551/21184204/0ae9b1c8-c214-11e6-8644-f7c4647f657b.png)

**Comment by kean** [comment]
Thanks, I'll investigate. However, I'm quite sure that's just the fasle negative. LinkedList is very simple and I've also tested Cache numerous times.

**Comment by n3trino** [comment]
@kean should i treat it as false positive memory leak?

**Comment by kean** [comment]
@n3trino sorry, I'm on a vacation, had no time to test this. I'm no entirely sure, but I believe that there is no leak, and this Cache object is a singleton anyway.

**Comment by kean** [comment]
I've done some extensive testing and can confirm that there are no leak neither in `Cache`, `LinkedList`, nor in any other Nuke classes. All the proper `deinit` methods get called, memory usage doesn't grow, etc.

I'm pretty sure it's just a false positive in Memory Graph Debugger, it's a new instrument after all. I wish I could get rid of that warning, but I have no idea how.

**Comment by winkelsdorf** [comment]
As addendum, I see several leaks - one related to `LinkedList<CachedImage>` too - but also in Profiler (Leak Mode).

In my case this only happens when routing Nuke through Alamofire (here in `AppDelegate`):
```swift
let loader = Nuke.Loader(loader: NukeAlamofirePlugin.DataLoader(), decoder: Nuke.DataDecoder(), cache: Cache.shared)
let manager = Nuke.Manager(loader: loader, cache: Cache.shared)
Nuke.Manager.shared = manager
```

For some of them, i.e. `NSLock()` and `LinkedList` my educated guess is, that the Profiler is reporting false positives.

AlamofireNetworkActivityIndicator had reportedly also had to deal with such a leak (now fixed with Xcode 8.2). See: https://github.com/Alamofire/AlamofireNetworkActivityIndicator/issues/19

@kean Hope you had a pleasant holiday! Can you confirm that routing through Alamofire does not create additional leaks in Nuke (not speaking of leaks probably related to false positives in Alamofire)?

Cheers
Frederik

**Without Nuke's Alamofire Routing**
<img width="1308" alt="screenshot 2017-01-20 12 08 22" src="https://cloud.githubusercontent.com/assets/1413291/22147763/82970d3e-df0a-11e6-913f-5bbaaf167c83.png">

**With Routing through Alamofire**
<img width="1388" alt="screenshot 2017-01-20 12 12 01" src="https://cloud.githubusercontent.com/assets/1413291/22147772/8fc3fa94-df0a-11e6-9daa-161ca869a96f.png">
<img width="1388" alt="screenshot 2017-01-20 12 12 34" src="https://cloud.githubusercontent.com/assets/1413291/22147775/93b32e68-df0a-11e6-8969-a6e65092568f.png">

**Comment by kean** [comment]
@winkelsdorf thank you for a such a detailed (as always) report! I'll investigate when I have some time to do so. I don't have a clear notion what's going on with those warnings right now.

**Comment by winkelsdorf** [comment]
@kean You're welcome! Thank you for your extensive support as always, too 👍 As said, I believe it to be a false positive.

**Comment by kean** [comment]
I've simplified memory management in Nuke 5 (not directly related to this issue, I'll give it some more attention later):

- [Nuke 5 Release Notes (Draft)](https://github.com/kean/Nuke/blob/master/CHANGELOG.md#nuke-50)
- [Nuke 5 Migration Guide (Draft)](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%205%20Migration%20Guide.md#nuke-5-migration-guide)

**Comment by winkelsdorf** [comment]
Looks already very elegant 👍 I had no time to implement it yet, but I guess it would break `Nuke-Alamofire-Plugin` at this stage?

**Comment by kean** [comment]
No worries. I'll update plugins alongside Nuke 5 beta.

**Comment by winkelsdorf** [comment]
Already though that, but I was sooo keen to try the new API ^^ Ok, I promise to be more patient 👍

**Comment by kean** [comment]
[Nuke 5](https://github.com/kean/Nuke/releases/tag/5.0) is out 🍾

**Comment by kean** [comment]
Xcode 8.3 seems to solve all those pesky false-positive memory leak warnings 🎉
